export const appData = {
  artists: [
    {
      id: 101,
      image: require("./images/Daft Punk.jpg"),
      nam: "Daft Punk",
      genre: "Pop",
      albums: [
        { id: 201, album_nam: "Fire", album_year: 2000, qty_song: 15 },
        { id: 202, album_nam: "Love", album_year: 2001, qty_song: 18 },
        { id: 203, album_nam: "Star", album_year: 2002, qty_song: 16 },
      ],
    },
    {
      id: 102,
      image: require("./images/Hans Zimmer.jpg"),
      nam: "Hans Zimmer",
      genre: "Jazz",
      albums: [
        { id: 301, album_nam: "Sun", album_year: 2005, qty_song: 15 },
        { id: 302, album_nam: "Luna", album_year: 2007, qty_song: 18 },
        { id: 303, album_nam: "Sea", album_year: 2010, qty_song: 16 },
      ],
    },
    {
      id: 103,
      image: require("./images/The Weeknd.jpg"),
      nam: "The Weeknd",
      genre: "Pop",
      albums: [
        {
          id: 401,
          album_img: require("./images/Take My Breath (Single Package) - Single.jpg"),
          album_nam: "Street",
          album_year: 2002,
          qty_song: 15,
        },
        {
          id: 402,
          album_img: "",
          album_nam: "Run",
          album_year: 2002,
          qty_song: 15,
        },
      ],
    },
    {
      id: 104,
      image: require("./images/Gorillaz.jpg"),
      nam: "Gorillaz",
      genre: "Alternative",
      albums: [
        { id: 501, album_nam: "Gorillaz", album_year: 2001, qty_song: 17 },
        {
          id: 502,
          album_nam: "Laika Come Home",
          album_year: 2002,
          qty_song: 12,
        },
        { id: 503, album_nam: "Daemon Days", album_year: 2005, qty_song: 15 },
        {
          id: 504,
          album_nam: "Plastic Beach (Deluxe Version)",
          album_year: 2010,
          qty_song: 18,
        },
        { id: 505, album_nam: "The Fall", album_year: 2010, qty_song: 15 },
        {
          id: 506,
          album_nam: "Humanz (Deluxe)",
          album_year: 2017,
          qty_song: 26,
        },
        { id: 507, album_nam: "The Now Now", album_year: 2018, qty_song: 11 },
        {
          id: 508,
          album_nam: "Song Machine, Season One:Strange Timez (deluxe)",
          album_year: 2020,
          qty_song: 17,
        },
        {
          id: 509,
          album_nam: "Cracker Island (Deluxe)",
          album_year: 2023,
          qty_song: 15,
        },
      ],
    },
    {
      id: 105,
      image: require("./images/Nirvana.jpg"),
      nam: "Nirvana",
      genre: "Rock",
      albums: [
        { id: 601, album_nam: "Fire", album_year: 2000, qty_song: 15 },
        { id: 602, album_nam: "Love", album_year: 2001, qty_song: 18 },
        { id: 603, album_nam: "Star", album_year: 2002, qty_song: 16 },
      ],
    },
    {
      id: 106,
      image: require("./images/Moby.jpg"),
      nam: "Moby",
      genre: "Electronic",
      albums: [
        { id: 701, album_nam: "Sun", album_year: 2005, qty_song: 15 },
        { id: 702, album_nam: "Luna", album_year: 2007, qty_song: 18 },
        { id: 703, album_nam: "Sea", album_year: 2010, qty_song: 16 },
      ],
    },
    {
      id: 107,
      image: require("./images/Justin Timerkake.jpg"),
      nam: "Justin Timberlake",
      genre: "Pop",
      albums: [
        { id: 801, album_nam: "Street", album_year: 2002, qty_song: 15 },
        { id: 802, album_nam: "Car", album_year: 2008, qty_song: 18 },
        { id: 803, album_nam: "Dog", album_year: 2022, qty_song: 16 },
      ],
    },
    {
      id: 108,
      image: require("./images/Depeche Mode.jpg"),
      nam: "Depeche Mode",
      genre: "Alternative",
      albums: [
        { id: 901, album_nam: "Gorillaz", album_year: 2001, qty_song: 17 },
        {
          id: 902,
          album_nam: "Laika Come Home",
          album_year: 2002,
          qty_song: 12,
        },
        { id: 903, album_nam: "Daemon Days", album_year: 2005, qty_song: 15 },
        {
          id: 904,
          album_nam: "Plastic Beach (Deluxe Version)",
          album_year: 2010,
          qty_song: 18,
        },
        { id: 905, album_nam: "The Fall", album_year: 2010, qty_song: 15 },
        {
          id: 906,
          album_nam: "Humanz (Deluxe)",
          album_year: 2017,
          qty_song: 26,
        },
        { id: 907, album_nam: "The Now Now", album_year: 2018, qty_song: 11 },
        {
          id: 908,
          album_nam: "Song Machine, Season One:Strange Timez (deluxe)",
          album_year: 2020,
          qty_song: 17,
        },
        {
          id: 909,
          album_nam: "Cracker Island (Deluxe)",
          album_year: 2023,
          qty_song: 15,
        },
      ],
    },
    {
      id: 109,
      image: require("./images/Red Hot Chili Peppers.jpg"),
      nam: "Red Hot Chili Peppers",
      genre: "Rock",
      albums: [
        { id: 1001, album_nam: "Street", album_year: 2002, qty_song: 15 },
        { id: 1002, album_nam: "Car", album_year: 2008, qty_song: 18 },
        { id: 1003, album_nam: "Dog", album_year: 2022, qty_song: 16 },
      ],
    },
  ],
};
